version: v0.6.0-alpha.1

log:
  level: debug

namespaces:
  - id: 0
    name: participants
  - id: 1
    name: roles
  - id: 2
    name: permissions

dsn: memory

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467
